# Workflow based off https://github.com/felipetofoli/dotnet-full-framework-ci-sandbox
name: Build and Tests

# Trigger this CI on push or for PRs
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5

      - name: Setup VSTest
        uses: darenm/Setup-VSTest@v1

      - name: Restore Packages
        run: nuget restore SimpCity.sln

      - name: Build Solution
        run: |
          msbuild.exe SimpCity.sln /p:platform="Any CPU" /p:configuration="Release"

      - name: Run Tests
        run: vstest.console.exe .\SimpCityTests\bin\Release\SimpCityTests.dll
