name: Build and Tests

# Workflow based off https://dev.to/felipetofoli/github-actions-for-net-full-framework-build-and-test-299h

on:  
  push:
    branches: [ cicd ]
  pull_request:
    branches: [ cicd ]

jobs:  
  build:    
    runs-on: windows-latest
    
    steps:      
      - uses: actions/checkout@v2
      
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5
        
      - name: Setup VSTest
        uses: darenm/Setup-VSTest@v1

      - name: Navigate to Workspace
        run: cd $GITHUB_WORKSPACE

      - name: Restore Packages
        run: nuget restore SimpCity.sln

      - name: Build Solution
        run: |
          msbuild.exe SimpCity.sln /p:platform="Any CPU" /p:configuration="Release"
        
      - name: Run Tests
        run: vstest.console.exe .\SimpCityTests\bin\Release\SimpCityTests.dll
